### ISSUE TITLE
missing chrome or chromium

### ISSUE THREAD

**Issue by TheNetyx** [privacyrespected/Alpha#7]
when i run usersettings i get this error message:
```
Traceback (most recent call last):
  File "usersettings.py", line 78, in <module>
  File "eel\__init__.py", line 142, in start
  File "eel\__init__.py", line 170, in show
  File "eel\browsers.py", line 65, in open
OSError: Can't find Google Chrome/Chromium installation
```
something similar happens when i run the python script instead:
```
Traceback (most recent call last):
  File "usersettings.py", line 53, in <module>
    eel.start("homesetting.html",cmdline_args=['--start-fullscreen'], port=1111)
  File "/home/netyx/.local/lib/python3.8/site-packages/eel/__init__.py", line 158, in start
    show(*start_urls)
  File "/home/netyx/.local/lib/python3.8/site-packages/eel/__init__.py", line 186, in show
    brw.open(start_urls, _start_args)
  File "/home/netyx/.local/lib/python3.8/site-packages/eel/browsers.py", line 65, in open
    raise EnvironmentError("Can't find %s installation" % browser_module.name)
OSError: Can't find Google Chrome/Chromium installation

```
I have chromium installed.

Edit: I can now run the python script after installing chrome but the exe still doesn't work. It would be nice if there is a way to run this without needing chrome

**Comment by privacyrespected** [comment]
The program now runs on edge by default now. Thanks
